In [1]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
v

[0.5, 0.75, 1.0, 1.5, 2.0]

In [2]:
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

In [5]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [6]:
import array
v = [0.5, 0.75, 1.0, 1.5, 2.0]
a = array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [7]:
type(a)

array.array

In [8]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [9]:
a.extend([5.0, 6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [10]:
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [11]:
a.append('string')

TypeError: must be real number, not str

In [12]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [13]:
b = a.tolist()

In [14]:
type(b)

list

In [15]:
import numpy as np

In [16]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
type(a)

numpy.ndarray

In [18]:
b = np.array(['a', 'b', 'c'])
b

array(['a', 'b', 'c'], dtype='<U1')

In [19]:
type(b)

numpy.ndarray

In [20]:
c = np.arange(2, 20, 2)
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
d = np.arange(8, dtype=np.float)
d

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [22]:
d[5:]

array([5., 6., 7.])

In [23]:
d[:2]

array([0., 1.])

In [24]:
d.sum()

28.0

In [25]:
d.std()

2.29128784747792

In [26]:
d.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [27]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [28]:
2 * d

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [29]:
d ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [30]:
2 ** d

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [31]:
d ** d

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [32]:
np.exp(d)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [33]:
np.sqrt(d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [34]:
np.sqrt(2.5)

1.5811388300841898

In [35]:
import math
math.sqrt(2.5)

1.5811388300841898

In [36]:
math.sqrt(d)

TypeError: only size-1 arrays can be converted to Python scalars

In [37]:
e = np.array([d, d * 2])
e

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [38]:
e[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [39]:
e[0,2]

2.0

In [40]:
e[:, 1]

array([1., 2.])

In [41]:
e.sum()   # Calculates the sum of all values.

84.0

In [42]:
e.sum(axis=0)    # Calculates the sum along the first axis; i.e., column-wise.

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [43]:
e.sum(axis=1)    # Calculates the sum along the second axis; i.e., row-wise.

array([28., 56.])

In [44]:
f = np.zeros((2, 3), dtype = 'i')
f

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [45]:
g = np.ones((2,3),dtype = 'i')
g

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [46]:
h = np.linspace(5, 15, 12)
h
# Creates a one-dimensional ndarray object with evenly spaced intervals between numbers; parameters used are start, end, and num (number of elements).

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

In [47]:
h.size

12

In [48]:
h.ndim    # The number of dimensions.

1

In [49]:
h.dtype   # The dtype of the elements.

dtype('float64')

In [50]:
c.shape

(9,)

In [51]:
np.shape(c)

(9,)

In [52]:
cr = c.reshape((3, 3))
cr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [53]:
cr.T

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [54]:
cr.transpose()

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [55]:
np.resize(c, (3, 1))

array([[2],
       [4],
       [6]])

In [56]:
np.resize(c, (1, 5))

array([[ 2,  4,  6,  8, 10]])

In [57]:
np.resize(c, (2, 4))

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [58]:
crr = np.resize(c, (4, 2))
crr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [59]:
np.hstack((crr, 2 * crr))

array([[ 2,  4,  4,  8],
       [ 6,  8, 12, 16],
       [10, 12, 20, 24],
       [14, 16, 28, 32]])

In [60]:
np.vstack((crr, 0.5 * crr))

array([[ 2.,  4.],
       [ 6.,  8.],
       [10., 12.],
       [14., 16.],
       [ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [61]:
crr.flatten()

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [62]:
crr > 5

array([[False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [63]:
(crr == 8).astype(int)

array([[0, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

In [64]:
(crr > 4) & (crr <= 12)

array([[False, False],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [65]:
crr[crr > 8]

array([10, 12, 14, 16])

In [66]:
crr[(crr > 4) & (crr <= 12)]

array([ 6,  8, 10, 12])

In [67]:
crr[(crr < 4) | (crr >= 12)]

array([ 2, 12, 14, 16])

In [68]:
np.where(crr % 2 == 0, 'even', 'odd')

array([['even', 'even'],
       ['even', 'even'],
       ['even', 'even'],
       ['even', 'even']], dtype='<U4')

In [69]:
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5

In [70]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [72]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [73]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [74]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [75]:
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [76]:
r.shape

(4, 3)

In [77]:
def f(x):
    return 3 * x + 5

In [78]:
f(0.5)

6.5

In [79]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

In [80]:
x = np.random.standard_normal((1000000, 5))
y = 2 * x + 3
C = np.array((x, y), order='C')    # This creates a two-dimensional ndarray object with C order (row-major).
F = np.array((x, y), order='F')    # This creates a two-dimensional ndarray object with F order (column-major).
C[:2].round(2)

array([[[-1.09,  0.1 ,  0.78, -1.15,  1.29],
        [ 0.87, -0.6 ,  1.17, -1.25,  1.35],
        [ 0.62,  1.64,  0.05,  1.35,  1.28],
        ...,
        [-1.7 , -0.28, -1.4 ,  1.12, -1.15],
        [ 0.42, -0.7 ,  0.14,  0.18, -1.  ],
        [ 0.07, -0.54, -0.53,  1.53, -0.02]],

       [[ 0.83,  3.21,  4.56,  0.7 ,  5.58],
        [ 4.75,  1.8 ,  5.34,  0.49,  5.69],
        [ 4.25,  6.27,  3.11,  5.7 ,  5.56],
        ...,
        [-0.4 ,  2.45,  0.19,  5.24,  0.71],
        [ 3.83,  1.59,  3.28,  3.37,  1.01],
        [ 3.13,  1.92,  1.94,  6.06,  2.95]]])

In [81]:
%timeit C.sum()

9.35 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [82]:
%timeit F.sum()

7.62 ms ± 899 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [83]:
import pandas as pd
df = pd.DataFrame([10, 20, 30, 40],
                  columns=['numbers'],
                  index=['a', 'b', 'c', 'd'])
df

numbers
a       10
b       20
c       30
d       40

In [84]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [85]:
df.columns

Index(['numbers'], dtype='object')

In [86]:
df.loc['c']

numbers    30
Name: c, dtype: int64

In [87]:
df.loc[['a', 'd']]

numbers
a       10
d       40

In [88]:
df.iloc[1:3]

numbers
b       20
c       30

In [89]:
df.sum()

numbers    100
dtype: int64

In [90]:
df.apply(lambda x: x ** 2)

numbers
a      100
b      400
c      900
d     1600

In [91]:
df ** 2

numbers
a      100
b      400
c      900
d     1600

In [92]:
df['floats'] = (1.5, 2.5, 3.5, 4.5)
df

numbers  floats
a       10     1.5
b       20     2.5
c       30     3.5
d       40     4.5

In [93]:
df['floats']

a    1.5
b    2.5
c    3.5
d    4.5
Name: floats, dtype: float64

In [94]:
df['names'] = pd.DataFrame(['Yves', 'Sandra', 'Lilli', 'Henry'],
index=['d', 'a', 'b', 'c'])
df

numbers  floats   names
a       10     1.5  Sandra
b       20     2.5   Lilli
c       30     3.5   Henry
d       40     4.5    Yves

In [95]:
df.append({'numbers': 100, 'floats': 5.75, 'names': 'Jil'},
ignore_index=True)

numbers  floats   names
0       10    1.50  Sandra
1       20    2.50   Lilli
2       30    3.50   Henry
3       40    4.50    Yves
4      100    5.75     Jil

In [96]:
df = df.append(pd.DataFrame({'numbers': 100, 'floats': 5.75,
'names': 'Jil'}, index=['y',]))
df

numbers  floats   names
a       10    1.50  Sandra
b       20    2.50   Lilli
c       30    3.50   Henry
d       40    4.50    Yves
y      100    5.75     Jil

In [97]:
df = df.append(pd.DataFrame({'names': 'Liz'}, index=['z',]),
sort=False)
df

numbers  floats   names
a     10.0    1.50  Sandra
b     20.0    2.50   Lilli
c     30.0    3.50   Henry
d     40.0    4.50    Yves
y    100.0    5.75     Jil
z      NaN     NaN     Liz

In [98]:
df.dtypes

numbers    float64
floats     float64
names       object
dtype: object

In [99]:
df[['numbers', 'floats']].mean()

numbers    40.00
floats      3.55
dtype: float64

In [100]:
df[['numbers', 'floats']].std()

numbers    35.355339
floats      1.662077
dtype: float64

In [101]:
a = np.random.standard_normal((9,4))
a


array([[ 1.92475673e+00,  1.87800958e+00,  1.02888934e+00,
        -1.44844825e+00],
       [ 3.88964469e-01,  5.33542043e-01,  1.78592134e+00,
        -3.05756090e+00],
       [ 8.58662880e-01, -2.75465904e-03, -2.77623984e-01,
        -2.63295936e-02],
       [ 3.21888418e-03, -1.17251077e+00, -6.80983099e-01,
         9.75436798e-01],
       [ 3.57740095e-02,  2.03942024e-01, -3.92037594e-01,
         1.30386989e-01],
       [ 1.68392373e+00, -1.14621988e+00, -2.20212959e-01,
        -9.31105120e-01],
       [ 1.26517114e+00, -7.90404098e-01, -1.50380196e-01,
        -1.25180424e-01],
       [-7.27887059e-04, -3.04272644e-01, -9.94685325e-01,
         4.83574816e-01],
       [ 1.38246908e-01,  4.17302452e-01, -8.06592588e-01,
        -6.98805949e-01]])

In [102]:
df = pd.DataFrame(a)
df

0         1         2         3
0  1.924757  1.878010  1.028889 -1.448448
1  0.388964  0.533542  1.785921 -3.057561
2  0.858663 -0.002755 -0.277624 -0.026330
3  0.003219 -1.172511 -0.680983  0.975437
4  0.035774  0.203942 -0.392038  0.130387
5  1.683924 -1.146220 -0.220213 -0.931105
6  1.265171 -0.790404 -0.150380 -0.125180
7 -0.000728 -0.304273 -0.994685  0.483575
8  0.138247  0.417302 -0.806593 -0.698806

In [103]:
df.columns = ['No1', 'No2', 'No3','No4']
df

No1       No2       No3       No4
0  1.924757  1.878010  1.028889 -1.448448
1  0.388964  0.533542  1.785921 -3.057561
2  0.858663 -0.002755 -0.277624 -0.026330
3  0.003219 -1.172511 -0.680983  0.975437
4  0.035774  0.203942 -0.392038  0.130387
5  1.683924 -1.146220 -0.220213 -0.931105
6  1.265171 -0.790404 -0.150380 -0.125180
7 -0.000728 -0.304273 -0.994685  0.483575
8  0.138247  0.417302 -0.806593 -0.698806

In [104]:
df['No2'].mean()

-0.042596216372181

In [105]:
dates = pd.date_range('2019-1-1', periods=9, freq='M')
dates

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30'],
              dtype='datetime64[ns]', freq='M')

In [106]:
df.index = dates
df

No1       No2       No3       No4
2019-01-31  1.924757  1.878010  1.028889 -1.448448
2019-02-28  0.388964  0.533542  1.785921 -3.057561
2019-03-31  0.858663 -0.002755 -0.277624 -0.026330
2019-04-30  0.003219 -1.172511 -0.680983  0.975437
2019-05-31  0.035774  0.203942 -0.392038  0.130387
2019-06-30  1.683924 -1.146220 -0.220213 -0.931105
2019-07-31  1.265171 -0.790404 -0.150380 -0.125180
2019-08-31 -0.000728 -0.304273 -0.994685  0.483575
2019-09-30  0.138247  0.417302 -0.806593 -0.698806

In [107]:
df.values

array([[ 1.92475673e+00,  1.87800958e+00,  1.02888934e+00,
        -1.44844825e+00],
       [ 3.88964469e-01,  5.33542043e-01,  1.78592134e+00,
        -3.05756090e+00],
       [ 8.58662880e-01, -2.75465904e-03, -2.77623984e-01,
        -2.63295936e-02],
       [ 3.21888418e-03, -1.17251077e+00, -6.80983099e-01,
         9.75436798e-01],
       [ 3.57740095e-02,  2.03942024e-01, -3.92037594e-01,
         1.30386989e-01],
       [ 1.68392373e+00, -1.14621988e+00, -2.20212959e-01,
        -9.31105120e-01],
       [ 1.26517114e+00, -7.90404098e-01, -1.50380196e-01,
        -1.25180424e-01],
       [-7.27887059e-04, -3.04272644e-01, -9.94685325e-01,
         4.83574816e-01],
       [ 1.38246908e-01,  4.17302452e-01, -8.06592588e-01,
        -6.98805949e-01]])

In [108]:
np.array(df)

array([[ 1.92475673e+00,  1.87800958e+00,  1.02888934e+00,
        -1.44844825e+00],
       [ 3.88964469e-01,  5.33542043e-01,  1.78592134e+00,
        -3.05756090e+00],
       [ 8.58662880e-01, -2.75465904e-03, -2.77623984e-01,
        -2.63295936e-02],
       [ 3.21888418e-03, -1.17251077e+00, -6.80983099e-01,
         9.75436798e-01],
       [ 3.57740095e-02,  2.03942024e-01, -3.92037594e-01,
         1.30386989e-01],
       [ 1.68392373e+00, -1.14621988e+00, -2.20212959e-01,
        -9.31105120e-01],
       [ 1.26517114e+00, -7.90404098e-01, -1.50380196e-01,
        -1.25180424e-01],
       [-7.27887059e-04, -3.04272644e-01, -9.94685325e-01,
         4.83574816e-01],
       [ 1.38246908e-01,  4.17302452e-01, -8.06592588e-01,
        -6.98805949e-01]])